<a href="https://colab.research.google.com/github/sinhoretti/Dio-desafio-GitHub-primeiro-repositorio/blob/main/While.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Escreva um sistema que lei a senha e compare se é verdadeira!
#Se estiver errada pede digitar a senha novamente!
contador=0
senha = "senai"
while contador==0:
  senha = input(print("\nDigite sua senha: "))
  if(senha == "senai"):
    print("Senha Correta! Acesso Liberado!")
    contador=1
    break
  else:
    print("Senha incorreta! Acesso Negado!")
    contador=0

Digite sua senha:
None1233
Senha incorreta! Acesso Negado!

Digite sua senha:
Nonesenai
Senha Correta! Acesso Liberado!

In [10]:
#Escreva um algoritmo para ler 2 valores e se o segundo for igual a ZERO, deve ser lido outro valor.
#após a leitura deverá ser impresso a divisão dos 2 numeros digitados
#o sistema deverá permitir o maximo de 3 tentativas para a digitação!
n1=int(input(print("Digite o 1º numero! "))) 
n2=int(input(print("Digite o 2º numero! ")))
tentativa=0;
while(n2==0):
  if(tentativa==2):
    print("\nTentativas esgotadas!")
    break
  while(tentativa<2):
    print("\nO segundo numero digitado é (0), digite outro numero diferente de zero! ")
    n2=int(input(print("Digite o 2º numero! ")))
    tentativa = tentativa + 1
    if(n2!=0):
      print("\nA divisão dos 2 numeros digitados é igual a: ", (n1/n2))
      divi = n1/n2
      print(f'A divisão de {n1} por {n2} é {divi}')
      break;

Digite o 1º numero!
None5
Digite o 2º numero!
None0

O segundo numero digitado é (0), digite outro numero diferente de zero!
Digite o 2º numero!
None0

O segundo numero digitado é (0), digite outro numero diferente de zero!
Digite o 2º numero!
None0

Tentativas esgotadas!

In [20]:
#Desenvolver um algoritmo que efetue a soma de todos os numeros impares que são multiplos de três e que se encontram no conjunto dos números de 1 até 500.
n = 0
soma = 0 
while(n<501):
  modulo=n%3
  n=n+1
  if(modulo==0):
    soma= soma+n
    print("\n",soma)

 1

 5

 12

 22

 35

 51

 70

 92

 117

 145

 176

 210

 247

 287

 330

 376

 425

 477

 532

 590

 651

 715

 782

 852

 925

 1001

 1080

 1162

 1247

 1335

 1426

 1520

 1617

 1717

 1820

 1926

 2035

 2147

 2262

 2380

 2501

 2625

 2752

 2882

 3015

 3151

 3290

 3432

 3577

 3725

 3876

 4030

 4187

 4347

 4510

 4676

 4845

 5017

 5192

 5370

 5551

 5735

 5922

 6112

 6305

 6501

 6700

 6902

 7107

 7315

 7526

 7740

 7957

 8177

 8400

 8626

 8855

 9087

 9322

 9560

 9801

 10045

 10292

 10542

 10795

 11051

 11310

 11572

 11837

 12105

 12376

 12650

 12927

 13207

 13490

 13776

 14065

 14357

 14652

 14950

 15251

 15555

 15862

 16172

 16485

 16801

 17120

 17442

 17767

 18095

 18426

 18760

 19097

 19437

 19780

 20126

 20475

 20827

 21182

 21540

 21901

 22265

 22632

 23002

 23375

 23751

 24130

 24512

 24897

 25285

 25676

 26070

 26467

 26867

 27270

 27676

 28085

 28497

 28912

 29330

 29751

 30175

 30602

 31032

 31465

 31901

 32340

 32782

 33227

 33675

 34126

 34580

 35037

 35497

 35960

 36426

 36895

 37367

 37842

 38320

 38801

 39285

 39772

 40262

 40755

 41251

 41750